OnekEsipe/Serveur

WebContent/WEB-INF/applicationContext.xml, WebContent/index.xhtml, WebContent/resources/css/style.css, src/main/java/com/onek/dao/LoginDao.java, src/main/java/com/onek/dao/LoginDaoImpl.java, src/main/java/com/onek/managedbean/LoginBean.java, src/main/java/com/onek/model/Candidat.java, src/main/java/com/onek/model/Critere.java, src/main/java/com/onek/model/Descripteur.java, src/main/java/com/onek/model/Evaluation.java, src/main/java/com/onek/model/Evenement.java, src/main/java/com/onek/model/Note.java, src/main/java/com/onek/model/Utilisateur.java, src/main/java/com/onek/service/LoginService.java, src/main/java/com/onek/service/LoginServiceImpl.java
=> Page login

WebContent/accueil.xhtml, src/main/java/com/onek/managedbean/AccueilBean.java
intégration du menu dans la page d'accueil+ ajout bouton création d'un événement
=> intégration du menu + ajout bouton création d'un event

WebContent/addJury.xhtml, WebContent/attributionJuryCandidat.xhtml, src/main/java/com/onek/dao/AddJuryDao.java, src/main/java/com/onek/dao/AddJuryDaoImpl.java, src/main/java/com/onek/dao/AttributionJCDao.java, src/main/java/com/onek/dao/AttributionJCDaoImpl.java, src/main/java/com/onek/managedbean/AddJuryBean.java, src/main/java/com/onek/managedbean/AttributionJCBean.java, src/main/java/com/onek/managedbean/EventAccueilBean.java, src/main/java/com/onek/service/AddJuryService.java, src/main/java/com/onek/service/AddJuryServiceImpl.java, src/main/java/com/onek/service/AttributionJCService.java, src/main/java/com/onek/service/AttributionJCServiceImpl.java
Front + modifications des liens de boutons sur les autres pages
=> Attribution jury candidat

WebContent/eventAccueil.xhtml, WebContent/index.xhtml, src/main/java/com/onek/dao/EventAccueilDao.java, src/main/java/com/onek/dao/EventAccueilDaoImpl.java, src/main/java/com/onek/managedbean/EventAccueilBean.java, src/main/java/com/onek/managedbean/EventBean.java, src/main/java/com/onek/managedbean/LoginBean.java, src/main/java/com/onek/service/EventAccueilService.java, src/main/java/com/onek/service/EventAccueilServiceImpl.java
correction du bouton de connexion
supprimer candidat d'un event
supprimer jury d'un event
=> modifications

WebContent/addCandidates.xhtml, WebContent/addJury.xhtml, WebContent/eventAccueil.xhtml, src/main/java/com/onek/dao/AddJuryDao.java, src/main/java/com/onek/dao/AddJuryDaoImpl.java, src/main/java/com/onek/dao/CandidatesDao.java, src/main/java/com/onek/dao/CandidatesDaoImpl.java, src/main/java/com/onek/dao/EventAccueilDaoImpl.java, src/main/java/com/onek/managedbean/AddJuryBean.java, src/main/java/com/onek/managedbean/CandidateBean.java, src/main/java/com/onek/managedbean/EventAccueilBean.java, src/main/java/com/onek/service/AddJuryService.java, src/main/java/com/onek/service/AddJuryServiceImpl.java, src/main/java/com/onek/service/CandidateService.java, src/main/java/com/onek/service/CandidateServiceImpl.java
suppression dynamique des candidats et des jurys 
quelques modifications et correction
=> Back creation event

pom.xml
Ajout de la conf pour qu'on voit le taux de couverture sur sonar
=> Jacoco test coverage

WebContent/addCandidates.xhtml, WebContent/addJury.xhtml, WebContent/attributionJuryCandidat.xhtml, WebContent/eventAccueil.xhtml, WebContent/grille.xhtml, WebContent/viewCreateEvent.xhtml, src/main/java/com/onek/managedbean/AccueilBean.java, src/main/java/com/onek/managedbean/AddJuryBean.java, src/main/java/com/onek/managedbean/AttributionJCBean.java, src/main/java/com/onek/managedbean/CandidateBean.java, src/main/java/com/onek/managedbean/EventAccueilBean.java, src/main/java/com/onek/managedbean/GrilleBean.java, src/main/java/com/onek/model/Critere.java, src/main/java/com/onek/utils/Navigation.java
Correction de la grille 
Toutes les pages utilisent bien l'événement sélectionné
=> Correction grille

WebContent/accueil.xhtml, WebContent/eventAccueil.xhtml, src/main/java/com/onek/managedbean/AccueilBean.java, src/main/java/com/onek/managedbean/AttributionJCBean.java, src/main/java/com/onek/managedbean/EventAccueilBean.java, src/main/java/com/onek/managedbean/EventBean.java, src/main/java/com/onek/managedbean/GrilleBean.java, src/main/java/com/onek/managedbean/LoginBean.java, src/main/java/com/onek/managedbean/MenuBean.java
=> Revert "ajout du refresh sur page acceuil event + Navigation"

WebContent/WEB-INF/applicationContext.xml, WebContent/addUser.xhtml, src/main/java/com/onek/dao/UserDao.java, src/main/java/com/onek/dao/UserDaoImpl.java, src/main/java/com/onek/managedbean/AccueilBean.java, src/main/java/com/onek/managedbean/UserBean.java, src/main/java/com/onek/service/UserService.java, src/main/java/com/onek/service/UserServiceImpl.java
suppression d'un utilisateur+bouton statut utilisateur(admin/orga)
=> Supprimer utilisateur

WebContent/account.xhtml, WebContent/accueil.xhtml, WebContent/menuorg.xhtml, WebContent/viewCreateEvent.xhtml, src/main/java/com/onek/dao/AcceuilDaoImpl.java, src/main/java/com/onek/dao/AccueilDao.java, src/main/java/com/onek/managedbean/AccueilBean.java, src/main/java/com/onek/service/AccueilService.java, src/main/java/com/onek/service/AccueilServiceImpl.java
Gestion des droits (Admin/Organisateur) pour la page accueil.xhtml : Done
=> Gestion droits

WebContent/WEB-INF/applicationContext.xml, WebContent/addCandidates.xhtml, WebContent/eventAccueil.xhtml, WebContent/viewCreateEvent.xhtml, src/main/java/com/onek/managedbean/AccueilBean.java, src/main/java/com/onek/managedbean/EventAccueilBean.java
gestion des statut event ok + modif mineur sur addcandidat
=> Gestion statut event

src/main/java/com/onek/controller/ApplicationController.java, src/main/java/com/onek/dao/EvaluationDao.java, src/main/java/com/onek/dao/EvaluationDaoImpl.java, src/main/java/com/onek/resource/EvaluationResource.java, src/main/java/com/onek/resource/NoteResource.java, src/main/java/com/onek/service/ApplicationService.java, src/main/java/com/onek/service/ApplicationServiceImpl.java
ajout et modif de note et d'évaluation OK
l'ensemble des tests ont été effectués
rejet si event non ouvert,
dateLastChangeNewEval < dateLastChangeEvalDb 
check des dates des notes 
si dateLastChangeNewEval > dateLastChangeEvalDb && dateLastChangeNewEval > date fin event
=> Maj import evaluation

src/main/java/com/onek/managedbean/EventAccueilBean.java
=> résolution du bug

WebContent/grille.xhtml, src/main/java/com/onek/managedbean/GrilleBean.java
=> Ajout niveau grille

WebContent/accueil.xhtml, WebContent/viewCreateEvent.xhtml, src/main/java/com/onek/managedbean/AccountBean.java, src/main/java/com/onek/managedbean/AccueilBean.java, src/main/java/com/onek/managedbean/CandidateBean.java, src/main/java/com/onek/managedbean/EventBean.java, src/main/java/com/onek/managedbean/UserBean.java
-Bug affichage date resolu
-Mise à plat des champs du formulaire après utilisation (porte sur
plusieurs ecrans)
=> Bug date et formulaire

src/main/java/com/onek/managedbean/AddJuryBean.java, src/main/java/com/onek/managedbean/AttributionJCBean.java, src/main/java/com/onek/managedbean/EventAccueilBean.java, src/main/java/com/onek/managedbean/EventBean.java, src/main/java/com/onek/managedbean/GrilleBean.java
=> Revert "Gestion des redirections"

WebContent/eventAccueil.xhtml, src/main/java/com/onek/dao/EvenementDao.java, src/main/java/com/onek/dao/EvenementDaoImpl.java, src/main/java/com/onek/dao/JuryDao.java, src/main/java/com/onek/dao/JuryDaoImpl.java, src/main/java/com/onek/managedbean/EventAccueilBean.java, src/main/java/com/onek/managedbean/EventBean.java, src/main/java/com/onek/service/EvenementService.java, src/main/java/com/onek/service/EvenementServiceImpl.java, src/main/java/com/onek/service/JuryService.java, src/main/java/com/onek/service/JuryServiceImpl.java
=> duplication event Back

WebContent/WEB-INF/applicationContext.xml, WebContent/statistiques.xhtml, src/main/java/com/onek/dao/EvaluationDao.java, src/main/java/com/onek/dao/EvaluationDaoImpl.java, src/main/java/com/onek/managedbean/StatistiquesBean.java, src/main/java/com/onek/service/EvaluationService.java, src/main/java/com/onek/service/EvaluationServiceImpl.java
- Avancement global de l'événement
- Avancement par jury
- Avancement par candidat
=> Ajout statistiques :

src/main/java/com/onek/managedbean/UserBean.java
vérification si l'user en question n'est pas le dernier admin dans la base
=> Suppression d'un user

WebContent/WEB-INF/applicationContext.xml, WebContent/addCandidates.xhtml, WebContent/addJury.xhtml, WebContent/attributionJuryCandidat.xhtml, WebContent/eventAccueil.xhtml, src/main/java/com/onek/managedbean/AttributionJCBean.java, src/main/java/com/onek/managedbean/EventAccueilBean.java
Pour addJury, addCandidate et attribJC
=> Gestion des suppressions en fonction du status

WebContent/addUser.xhtml, src/main/java/com/onek/managedbean/UserBean.java
verification mail ok + affichage dans popup des messages d'erreur (logindeja existant/email deja existant)
=> verification mail ok 

WebContent/WEB-INF/applicationContext.xml, WebContent/accueil.xhtml, WebContent/addCandidates.xhtml, WebContent/addJury.xhtml, WebContent/eventAccueil.xhtml, src/main/java/com/onek/managedbean/AccueilBean.java, src/main/java/com/onek/managedbean/EventAccueilBean.java
modification de la page accueilEvent
correction des barres de recherche des tableaux
ajout du bouton supprimer event à l'accueilEvent
ajout bouton récupérer event supprimé pour l'administrateur
=> Correction bug recherche

src/main/java/com/onek/controller/ApplicationController.java, src/main/java/com/onek/service/ApplicationService.java, src/main/java/com/onek/service/ApplicationServiceImpl.java, src/main/java/com/onek/service/UserServiceImpl.java
hash ajouter jury gérer par l'application
le mot de passe doit être haché pour se loguer
tous les mots de passe envoyés à l'application sont hachés
=> hash add jury gérer par app

WebContent/WEB-INF/applicationContext.xml, src/main/java/com/onek/dao/CandidatesDao.java, src/main/java/com/onek/dao/CandidatesDaoImpl.java, src/main/java/com/onek/dao/JuryDao.java, src/main/java/com/onek/dao/JuryDaoImpl.java, src/main/java/com/onek/managedbean/AddJuryBean.java, src/main/java/com/onek/managedbean/AttributionJCBean.java, src/main/java/com/onek/managedbean/CandidateBean.java, src/main/java/com/onek/managedbean/GrilleBean.java, src/main/java/com/onek/model/Candidat.java, src/main/java/com/onek/model/Critere.java, src/main/java/com/onek/model/Utilisateur.java, src/main/java/com/onek/service/CandidateService.java, src/main/java/com/onek/service/CandidateServiceImpl.java, src/main/java/com/onek/service/EventAccueilService.java, src/main/java/com/onek/service/EventAccueilServiceImpl.java, src/main/java/com/onek/service/JuryService.java, src/main/java/com/onek/service/JuryServiceImpl.java
modification de accueileventService
rajout equals hashcode dans utilisateur, grille, candidat
modification de jurydao,service,bean et candidatdao,service,bean
=> Nettoyage code

WebContent/accueil.xhtml, WebContent/eventAccueil.xhtml, WebContent/grille.xhtml, src/main/java/com/onek/managedbean/AccueilBean.java, src/main/java/com/onek/managedbean/EventAccueilBean.java, src/main/java/com/onek/managedbean/GrilleBean.java, src/main/java/com/onek/model/Evenement.java
Plein de motif graphique + corrections de bug
=> Modification affichage des descripteurs de criteres

src/main/java/com/onek/dao/UserDaoImpl.java, src/main/java/com/onek/managedbean/AccountBean.java, src/main/java/com/onek/managedbean/LoginBean.java, src/main/java/com/onek/service/UserServiceImpl.java, src/test/java/com/onek/beanstest/LoginBeanTest.java, src/test/java/com/onek/daotest/UserDaoTest.java, src/test/java/com/onek/servicetest/UserServiceTest.java
=> ajout de tests

WebContent/account.xhtml
Mise au même niveau des 2 panels
=> Design mon compte

WebContent/resources/css/header_footer.css, WebContent/resources/css/user.css
Erreur due au css créé specialement pour header/footer
=> Correction des inputs avec une taille bizarre

WebContent/addCandidates.xhtml, src/main/java/com/onek/dao/CandidatesDaoImpl.java, src/main/java/com/onek/managedbean/CandidateBean.java
UIX page candidat + resolution pbl de la suppression + boutton suppression de tous les candidats
=> Gestion candidats design

WebContent/addCritere.xhtml, WebContent/grille.xhtml, src/main/java/com/onek/dao/CritereDao.java, src/main/java/com/onek/dao/CritereDaoImpl.java, src/main/java/com/onek/dao/DescripteurDao.java, src/main/java/com/onek/dao/DescripteurDaoImpl.java, src/main/java/com/onek/managedbean/GrilleBean.java, src/main/java/com/onek/service/GrilleService.java, src/main/java/com/onek/service/GrilleServiceImpl.java
=> Modification d'un critère OK

WebContent/resources/css/style.css, WebContent/statistiques.xhtml, src/main/java/com/onek/managedbean/StatistiquesBean.java
la liste des jury n'ayant pas noté/pas fini pour les candidats
=> Ajout de la liste des candidats non/partiellement noté pour les jurys et

src/main/java/com/onek/managedbean/AddJuryBean.java, src/main/java/com/onek/managedbean/EventAccueilBean.java, src/main/java/com/onek/managedbean/EventBean.java, src/main/java/com/onek/utils/Password.java
manière plus poussée
La classe Password possède maintenant toutes ses méthodes en static
=> L'id de l'événement est maintenant à la fin pour éviter les doublons de

WebContent/account.xhtml, WebContent/addCandidates.xhtml, WebContent/addCritere.xhtml, WebContent/addJury.xhtml, WebContent/addUser.xhtml, WebContent/attributionJuryCandidat.xhtml, WebContent/eventManager.xhtml, WebContent/statistiques.xhtml, WebContent/viewCreateEvent.xhtml, src/main/java/com/onek/managedbean/AccountBean.java, src/main/java/com/onek/managedbean/CandidateBean.java, src/main/java/com/onek/managedbean/EventAccueilBean.java, src/main/java/com/onek/utils/Navigation.java
=> Focus menu msg error amelioration design

WebContent/addCandidates.xhtml, WebContent/addCritere.xhtml, src/main/java/com/onek/managedbean/CandidateBean.java
modification nom du critère
modification nom du bouton envoyer
=> homonymes importer OK

WebContent/eventManager.xhtml
=> Tooltip event

WebContent/statistiques.xhtml, src/main/java/com/onek/managedbean/StatistiquesBean.java
=> Statistiques % sur les critères OK + renommage de la colonne Note en

WebContent/attributionJuryCandidat.xhtml, src/main/java/com/onek/managedbean/AttributionJCBean.java
=> disabled checkbox si l'evenement n'est pas en statut Brouillon(on peut

WebContent/addCandidates.xhtml, src/main/java/com/onek/managedbean/CandidateBean.java, src/main/java/com/onek/model/Candidat.java
correction bug homonymes
modification paramètre et description import fichier csv
télécharger un modèle sur la base de la liste existante
=> Paramètre csv

WebContent/account.xhtml, WebContent/addCritere.xhtml, WebContent/grille.xhtml
Ajout du JS pour la fermeture de la pop-up de modification d'un
utilisateur
=> Correction de l'espacement des critères + taille en %

WebContent/addCandidates.xhtml, src/main/java/com/onek/managedbean/CandidateBean.java
=> Revert "changement séparateur csv"

src/main/java/com/onek/managedbean/CandidateBean.java, src/main/java/com/onek/managedbean/EventAccueilBean.java
homonyme
Message d'erreur quand on essaye de passer en ouvert sans critères
=> Correction de la faute d'orthographe lors de l'ajout d'un candidat
